<a href="https://colab.research.google.com/github/AFBA1993/DeepLearningTutorials/blob/main/RBM/filmes_bolztman.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from rbm import RBM
import numpy as np

In [8]:
rbm = RBM(num_visible = 6, num_hidden = 2)

In [9]:
base = np.array([[1,1,1,0,0,0],
                 [1,0,1,0,0,0],
                 [1,1,1,0,0,0],
                 [0,0,1,1,1,1],
                 [0,0,1,1,0,1],
                 [0,0,1,1,0,1]])

In [19]:
filmes = ["A bruxa", "Invocação do mal", "O chamado",
          "Se beber não case", "Gente grande", "American pie"]

In [10]:
rbm.train(base, max_epochs = 5000)

Epoch 0: error is 9.037742765167769
Epoch 1: error is 8.95547652755263
Epoch 2: error is 8.772804627913839
Epoch 3: error is 8.596266244207289
Epoch 4: error is 8.434045502707749
Epoch 5: error is 8.361508842936837
Epoch 6: error is 8.229099047109816
Epoch 7: error is 8.218209611711169
Epoch 8: error is 7.992507185355951
Epoch 9: error is 7.801203114456765
Epoch 10: error is 7.671379136882401
Epoch 11: error is 7.767541582833055
Epoch 12: error is 7.684101202093705
Epoch 13: error is 7.525892492309128
Epoch 14: error is 7.523033867879769
Epoch 15: error is 7.479849797471105
Epoch 16: error is 7.69633927756427
Epoch 17: error is 7.398918049784916
Epoch 18: error is 7.290642313747625
Epoch 19: error is 7.419605647484864
Epoch 20: error is 7.506514179506171
Epoch 21: error is 7.017873196969665
Epoch 22: error is 7.342396588106101
Epoch 23: error is 7.290652599633789
Epoch 24: error is 6.901967337945685
Epoch 25: error is 6.918256715970614
Epoch 26: error is 7.131110022229764
Epoch 27: err

In [11]:
rbm.weights

array([[ 2.4794893 ,  2.33346008,  0.41641418],
       [-1.02064945, -3.28558778,  7.9349407 ],
       [ 0.21733802, -7.22639064,  3.33789127],
       [ 4.94778031,  3.90751047,  1.91271331],
       [ 0.9448822 ,  3.62621177, -8.22807252],
       [-1.31138188,  0.60652544, -4.55324997],
       [ 0.94991583,  3.62236817, -8.23058698]])

In [22]:
usuario1 = np.array([[1,1,0,1,0,0]])
usuario2 = np.array([[0,0,0,1,1,0]])
rbm.run_visible(usuario1)

array([[0., 1.]])

In [17]:
camada_escondida = np.array([[0,1]])
recomendacao = rbm.run_hidden(camada_escondida)
recomendacao

array([[1., 1., 1., 0., 0., 0.]])

In [21]:
for i in range(len(usuario1[0])):
  if usuario1[0,i] == 0 and recomendacao[0,i] ==1:
    print(filmes[i])


O chamado
